import type { Metadata } from 'next';
import dynamic from 'next/dynamic';
import { Inter } from 'next/font/google';
import './globals.css';
import { Header } from './components/header/Header';
import { PrismicPreview } from '@prismicio/next';
import { repositoryName } from '@/prismicio';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PrismicPreview repositoryName={repositoryName} />
        <Header />

        <main className="main">
          <section className="main-wrapper">{children}</section>
        </main>
        <div id="portal"></div>
      </body>
    </html>
  );
}
