// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  fall_bros: dynamic(() => import("./FallBros")),
  hero: dynamic(() => import("./Hero")),
};
